apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "extends": [
        "github>davydehaas98/renovate-config:default.json"
      ],
      "baseBranches": [
        "main"
      ],
      "ignorePaths": ["disabled/**"],
      "argocd": {
        "fileMatch": ["\\.yaml$"]
      }
    }
