pms:
  configStorage: 10Gi

  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 50m

ingress:
  enabled: true
  url: plex.cloud.davydehaas.dev

extraEnv:
  PLEX_CLAIM: "claim"
