pms:
  configStorage: 10Gi

  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 50m

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    external-dns.alpha.kubernetes.io/hostname: plex.cloud.davydehaas.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  url: plex.cloud.davydehaas.dev

extraEnv:
  PLEX_CLAIM: "claim"
