---
# Install Ansible collections
collections:
  - name: community.general
    version: 8.6.1
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: 3.0.1
    source: https://galaxy.ansible.com