{{ range $k, $v :=.Values.applications }}
{{ if $v.deploy }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "base.productName" (dict "key" $k "value" $v) }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{ if $v.autoSync }}
  project: always-sync
  {{ else }}
  project: no-sync
  {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default (include "base.productName" (dict "key" $k "value" $v)) $v.namespace }}
  source:
    repoURL: git@github.com:davydehaas98/gitops.git
    targetRevision: HEAD
    path: applications/{{ include "base.productName" (dict "key" $k "value" $v) }}
  revisionHistoryLimit: 2
  {{- with $v.ignoreDifferences }}
  ignoreDifferences: {{ toYaml $v.ignoreDifferences | nindent 4 }}
  {{- end }}
  syncPolicy:
    {{ if $v.serverSideApply }}
    syncOptions:
      - ServerSideApply=true
    {{ end }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
---
{{ end -}}
{{ end -}}
