apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: 0 5 * * *
  task: "backup"
  groups:
    - default
  retain: 1
  concurrency: 4
