configs:
  cm:
    exec.enabled: true

  secret:
    createSecret: true

  params:
    server.insecure: true

controller:
  replicas: 1

  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

dex:
  enabled: false

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: argocd.cloud.davydehaas.dev
      external-dns.alpha.kubernetes.io/ttl: "120"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - argocd.cloud.davydehaas.dev
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.cloud.davydehaas.dev

  ingressGrpc:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: grpc.argocd.cloud.davydehaas.dev
      external-dns.alpha.kubernetes.io/ttl: "120"
      ingress-class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
      - grpc.argocd.cloud.davydehaas.dev
    tls:
      - secretName: argocd-grpc-tls
        hosts:
          - grpc.argocd.cloud.davydehaas.dev

  configEnabled: false

  rbacConfigCreate: false
repoServer:
  replicas: 1

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  enabled: false

notifications:
  enabled: false
