apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-server-vpa
  namespace: argocd
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: argocd-server
  updatePolicy:
    updateMode: "Off"
