crds:
  enabled: false

nodeExporter:
  enabled: true

prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Europe/Amsterdam

  replicas: 1

  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: grafana.cloud.davydehaas.dev
      external-dns.alpha.kubernetes.io/ttl: "120"
      ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - grafana.cloud.davydehaas.dev
    tls:
      - hosts:
          - grafana.cloud.davydehaas.dev
        secretName: "grafana-tls"

prometheus:
  enabled: true

  serviceAccount:
    create: true
  serviceMonitor:
    selfMonitor: true

  prometheusSpec:
    retention: 730d
    replicas: 1
    shards: 1

    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

    scrapeInterval: "30s"

    resources:
      limits:
        memory: 4096Mi
      requests:
        cpu: 100m
        memory: 2048Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

cleanPrometheusOperatorObjectNames: true
