crds:
  enabled: false

nodeExporter:
  enabled: true

prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true

grafana:
  enabled: false
  forceDeployDashboards: true

prometheus:
  enabled: true

  serviceAccount:
    create: true
    
  serviceMonitor:
    selfMonitor: true


  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      external-dns.alpha.kubernetes.io/hostname: prometheus.cloud.davydehaas.dev
      external-dns.alpha.kubernetes.io/ttl: "120"
      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    hosts:
      - prometheus.cloud.davydehaas.dev
    tls:
      - hosts:
          - prometheus.cloud.davydehaas.dev
        secretName: prometheus-tls

  prometheusSpec:
    retention: 730d
    replicas: 1
    shards: 1

    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

    scrapeInterval: "30s"

    resources:
      limits:
        memory: 4096Mi
      requests:
        cpu: 100m
        memory: 2048Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

cleanPrometheusOperatorObjectNames: true
