---
- name: Check if control-plane is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Install kube-vip
  ansible.builtin.shell: |
    export VIP=192.168.10.10
    export INTERFACE=eth0
    export KVVERSION=v0.8.0
    alias kube-vip="ctr image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"

- name: Install kube-vip manifest
  ansible.builtin.shell: |
    kube-vip manifest pod \
      --interface $INTERFACE \
      --address $VIP \
      --controlplane \
      --arp \
      --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml

- name: Copy kubeadm-config.yaml
  when: not kubeadm_init.stat.exists
  ansible.builtin.copy:
    src: ../../../../kubeadm-config.yaml
    dest: ~/kubeadm-config.yaml
    mode: '644'

- name: Initialize the control-plane
  when: not kubeadm_init.stat.exists
  ansible.builtin.command: kubeadm init --config ~/kubeadm-config.yaml --upload-certs
  changed_when: true

- name: Copy admin.conf
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: '755'
    remote_src: true

- name: Fetching Kubernetes Master PKI files from primary master
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /tmp/kubeadm-ha/pki/{{ item }}
    flat: true
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key

- name: Fetching Kubernetes Master ETCD files from primary master
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/etcd/{{ item }}
    dest: /tmp/kubeadm-ha/pki/etcd/{{ item }}
    flat: true
  with_items:
    - ca.crt
    - ca.key

- name: Fetching Kubernetes Master Admin files from primary master
  ansible.builtin.fetch:
    src: /etc/kubernetes/{{ item }}
    dest: /tmp/kubeadm-ha/{{ item }}
    flat: true
  with_items:
    - admin.conf
