---
- name: Check if control plane is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Install kube-vip
  become: true
  become_user: root
  ansible.builtin.shell: |
    export KUBE_VIP_VERSION=v0.8.0
    ctr image pull ghcr.io/kube-vip/kube-vip:$KUBE_VIP_VERSION
    alias kube-vip="ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KUBE_VIP_VERSION vip /kube-vip"

- name: Install kube-vip manifest
  become: true
  become_user: root
  ansible.builtin.shell: |
    export VIP=192.168.2.247
    export INTERFACE=eth0
    kube-vip manifest pod \
      --interface $INTERFACE \
      --address $VIP \
      --controlplane \
      --arp \
      --leaderElection \
      --enableLoadBalancer | tee /etc/kubernetes/manifests/kube-vip.yaml

- name: Copy kubeadm-config.yaml
  when: not kubeadm_init.stat.exists
  become: true
  become_user: root
  ansible.builtin.copy:
    src: ../../../../kubeadm-config.yaml
    dest: ~/kubeadm-config.yaml
    mode: '644'

- name: Initialize control plane
  when: not kubeadm_init.stat.exists
  become: true
  become_user: root
  # ansible.builtin.command: kubeadm init --control-plane-endpoint node-rk1 --pod-network-cidr 10.244.0.0/24
  ansible.builtin.command: kubeadm init --config ~/kubeadm-config.yaml --upload-certs
  # changed_when: true

- name: Create '.kube' directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: '{{ USER }}'
    mode: '755'

- name: Copy admin.conf
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ USER }}/.kube/config
    owner: '{{ USER }}'
    mode: '600'
    remote_src: true

- name: Fetching Kubernetes Master PKI files from primary master
  become: true
  become_user: root
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /tmp/kubeadm-ha/pki/{{ item }}
    flat: true
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key

- name: Fetching Kubernetes Master ETCD files from primary master
  become: true
  become_user: root
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/etcd/{{ item }}
    dest: /tmp/kubeadm-ha/pki/etcd/{{ item }}
    flat: true
  with_items:
    - ca.crt
    - ca.key

- name: Fetching Kubernetes Master Admin files from primary master
  become: true
  become_user: root
  ansible.builtin.fetch:
    src: /etc/kubernetes/{{ item }}
    dest: /tmp/kubeadm-ha/{{ item }}
    flat: true
  with_items:
    - admin.conf
