---
- name: Add Cilium repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: '{{ CILIUM_VERSION }}'
    namespace: kube-system
    values:
      operator.replica: 1
      kubeProxyReplacement: strict
