---
- name: Install Kubectl
  ansible.builtin.include_tasks: install_kubectl.yaml

- name: Initialize control plane
  ansible.builtin.include_tasks: init_control_plane.yaml

- name: Install Helm
  ansible.builtin.include_tasks: install_helm.yaml

- name: Install Cilium
  ansible.builtin.include_tasks: install_cilium.yaml

- name: Install Argo CD
  ansible.builtin.include_tasks: install_argocd.yaml
