apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgBO77K6kouJPL7ZFn01zlSA1143PBvCazZGG0f6zSzZ6PU7x6+pDghoghnvETYDjvme9xfqTchNSUULq2MuMdVF/PxkFnnl0VdXAfBIbbPGIgYK89GFJzJaDJfqthWHkacwXcz9gK4VUp83EIUyDXMDfN5Yt07CdphKsCipC9cRATELrLs83F4orSNI+VvOUlbdtPSdcAgf0u/ZGZEePFYJGwz95xQV6M6PXizMFFo0qsloiwDgSvehuqGJxon0Q2+DPVT5MzhhNm9J7bACnxvyvgxSyeVSEw/ADzi6AweZvLufU6TG+WhaxFQnw5TXe+1MqltdNQo4KsjJrSEE6/+SRl6aljWQmMrY6ZDCufRGAuqNE3x955jzfC9r6HWJ7O9px42M6UmPNIDuwNrYuqLf++H62bnvGkQLU4REdcaXCHVO0uomcf/EjejM0WDcXSiUESKFrFV5YRr6/pbSF1x2Zta48P46nXXXc7HYndo9Wc7HnsQSpwiXMCPJgaVCXVnnvfKyvdsSioFYTZD++ROdjs/cXg3REmjYEa3EZRIWgPv6vvjfGmypF4SXrdqgRmEw867SJcfWm4xKkkh5BF+LKRpx0SSS0ZHslgCQbS3/Gjx2690yTG7x62IRwXIEhDudw+5aOmVqJPMixPpQo3MmiJRoeLTjFniG3TtmhYqVQoFvrgGK1ZREw1P2BoagVCnUtp1efnIIySO/46H9esdiAXw3
    replication-password: AgBZ+fbANmEEC9hx91xPIuH7SIUy81LP41RDCtSV9WsK7pNUfAwQ7ifwRr8p8V93sOLZEsbEGi9KSI9eD+zMD8YPbD5MBFY7zFxsEy23gB4mOrxXBp7gXXoSB+crwC8ZXNkdO+qAnVfAdslJUpA1UsORV+OPZ8Ok8UpDzPaUh7p1jsr0mwaTbHnOqwXK0sAKdezAcoN5NZmPYymapOSdOxOdnJ7Yg6UGsv+EP6tTilIDlwkdSEznAeZNYcvNA6bP6ztXp8C8UCDa5G9bPOl6lm+/RBsfk4CinDY5cv9kG/w2tF07kRmNffSgFMOAl5OudPG+UD3LD6NhxCGZ53j/T4e7RxqLUGJcqEPAbrIS9XjYZIZ7mvLwNyrSijO7GcFYBcb3zPvcXP8Ot+/m/HnfXNnhGGBO/mvQGgQxmBoPafwlJ0xZAiVWIuqRjXB69lnDpYYvfT87FdZDqbzBcmMRsVRRpmBsOyYPxDLzjf3Vbe0zTs8WZRxQzJ3QrkBzsogwypYfawq5WcxPJF2lKOHcDzAxQ9iYeMFreJhcGATekwKJq3PoFSSESGm3wZ99Mdo+m3ioMrAy1KHfyZfeJmApJjBghtCH235TWwFPwV++BxRpKUykF7sYfXqUy+oepYnRnV+V0nc/xMYlHZZw37S5C5BHkeBe4+R6g/427ox2iVFRJWDafRfV2A+xFfSRCNY0FKJoSSGtyyhZ648vHF/Dv/yKxkL0TQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: postgresql
    type: Opaque
