apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-credentials
  namespace: minio
spec:
  encryptedData:
    secretKey: AgCBqRiYbPSH96q3UB50Cz5cro3SpZFcI85G64IZ4GqkAV4KSAYv4vBjBN7xgQ9sn7+1j5Vlr2i28ymWyyAa1oDGR/qXpDGPIWUuLnUodO1AiDYy2Ggj9oMRKhRdjt9ZGXdeYbEGHIXoIPEkvlLnBZJookcMpM5I9fpzzFcDTVtQ1V0C4su6aFgyy9zjPKDlXd6+EfqSQNiYmLIJSRQribsdQa3KOkh73EnGPPuE66Kd5ap8bPjUBvc6YR/+V5KLcKfyJoS154lsD5YTVrnxEmYa0M3itz7GRgE3s36ErpCr+Zu7bKma5ZtlfD/Y1iu3kdYN4OC10hHQl48Jk8HJvoNn1oIfwQOTRlFGszSgpqtf2CZnROcCEeN+7WhgLQ9tcJrz4SVMo4VZTJMBcpVULYUef/MIbN9rFy9uiAn33kcpjfpJ003jEHe2qGAKBEj2/EOfnXAxEcQHpxNpZ2i/bAIQ29R8kHgRsGT3A6JSDSAY43ZzPF0z21kZdLjzqj1HvrN7RrB/kYIbGNMoMJRG/GEDgK6ttGcY40Ts20onfty7R/d3StWCjG0Xye9ldBMQ4pXRb8nTFvYYlhoSoCIlwEX5EFMjLv0h+f4C6pyKoVtMdmNJ1xsYzA4nHGA1k+VzDNj5F+v76EpYUEtN/iHHYjShgCQVAkrFBOU6Vh0/cqqiFUpISv7EYDbP+76/bLGi7Os=
  template:
    metadata:
      creationTimestamp: null
      name: loki-credentials
      namespace: minio
