apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-credentials
  namespace: minio
spec:
  encryptedData:
    secretKey:
  template:
    metadata:
      creationTimestamp: null
      name: loki-credentials
      namespace: minio
