apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCQ8+yF/goWjoXyc10yOOcZuh66x6Vn83yPh06rNDkQWkJRduIsNra31CcD83qBgwOMwKIJT4mHlOPy9ibrCtCtSe6XqkgMe+iM8Mlwihzbs5WHbtpHpeOe6LQ/+uO1fjzGORtklzepgzJaYxZtS+IP6AwsPpakuYT9EjsMbewwK9BFDLFtw1u6urnDbl9VGKxlsLwXWHljD7PsP3PJ9J6sidbxNUHq2su2BTjKZ8QjuT1/Pm7O5XCQQOuTT4+S9B+1SCvr+bPk5NJbKjB4dq7EySg1c6QticMswSMhqfnE4bU4jI0C4bxgRRM7+XsACPUkV+dMQWRVc7QOzZqhi3i7yfyq1lzeA3Zo6+wfgfYpL9WqU1OyEI5upigtNhvNjZGLpmWM3FmU5WDy5uWH6acBXr/hznsZAvPPWy9jlBIHCHGJe0kwKfmX/PhGi5usoYWb6cxIEI44CJjYh/gvL7rMg9oL8VzRxpFO3fSgnbTDrjx+YEGRS9UuTokXzByxrbKpLvoovkDKvawac41LjTOa7JKeYlJn7qlABVbVZIwttxOfBecUQFViXh1aKGhJk1D9ramf7QoF+ZoDaUs8b+o9RE2ZnjeGVPs/HS56paidiD9pqLa0TtzYVi8/COWE/+MemTHjXmpFrHYFlg0x18BEYOtqXQ3haGtfWOpvenxsABh+MegvCOg4sth7ERWa6Qkaf1fCmkca6HWScuItVMrzAUowGw==
    rootUser: AgBAdZ1sPwILI6xZVkh7DUAoeBNuBWzfaRZ8218tF4zuaWIgO0sHeBo4sIqejP1GHBT9yGb1O5eV9CQj+/y0EYht7fNAg9/rbTSVQwd9n4WfBv2dbnIvhrzmq1jKIMsHBbKMn2DCX1L3A1gjO2ixshFWuVjKFdVAkWVkRFGBFK0KqJg+6oQbDbWtfSlUih0y/IvIbCN6YnCqvhjR6oNPsM/30ppxpvN/MPd5etq02SsoKexvOPw7grNkRNIo+EGTAXNIWFiX041apyCQ3j1miLSaoMl07kZ2rMx9yID1u1oLS0oD+9JUQeF+ZiTzl47eBiRJ13oGQ1H5mker2O0fcXwN4akXxcTQEs/9kqtWE5iWaDtA5bf1Jm5rYbi+EfjnZ3VevG8k5DuPsJ9dtUc0H8fbPaGtMySzaEYS3U62aC7vZbnmjh1MTD8Pj8A3i1gxCmiyv+Di8HA1Xx/CSKBfVjluIeoe4fy8+qdnuYdEGA6qt6wahnsr64f5e9dxSKm6h54ehj3mEmYsMT8L59pjAgC9yi9ahwsG06egbXvVTAiKiwbDxodgabnyqN2Nmi0EAuhA57vj0ybmnXdAB7h7DcC/mqhXipwDTSzPUYe4RZO3p5muWsKHW9akkKr9st568HwBcuXqV25NwaPumTYXwazufwkJje5bwngijw2esBHQfcAneNIUNG0HGYmQwEpI1jYB4Mb31pG2MOw7
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
