apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword:
    rootUser:
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
