replicaCount: 1

phpClientHttpsFix:
  enabled: true
  protocol: https

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: drive.cloud.davydehaas.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;

      rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }

  tls:
    - secretName: nextcloud-tls
      hosts:
        - drive.cloud.davydehaas.dev

nextcloud:
  host: drive.cloud.davydehaas.dev

  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

  mail:
    enabled: false

redis:
  enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 16Gi

resources:
  limits:
    cpu: null
    memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi
