pihole:
  DNS1: 1.1.1.1
  DNS2: 1.0.0.1

  persistentVolumeClaim:
    enabled: true
    accessMode: ReadWriteOnce
    size: 500Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      external-dns.alpha.kubernetes.io/hostname: pihole.cloud.davydehaas.dev
      external-dns.alpha.kubernetes.io/ttl: "120"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    path: /admin
    hosts:
      - pihole.cloud.davydehaas.dev
    tls:
      - secretName: pihole-tls
        hosts:
          - pihole.cloud.davydehaas.dev

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
