---
- name: Check if control plane is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Get join command
  when: not kubeadm_init.stat.exists
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: '{{ groups["control_plane_primary"][0] }}'
  changed_when: true

- name: Join control plane
  when: not kubeadm_init.stat.exists
  ansible.builtin.command: '{{ join_command.stdout_lines }}'
  changed_when: true
