apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb
spec:
  addresses:
  - 141.148.235.200/32
  autoAssign: true
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: l2-advertisement
#   namespace: metallb
# spec:
#   ipAddressPools:
#   - default
