apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip-pool
  namespace: metallb
spec:
  addresses:
  - 38.242.242.71/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - public-ip-pool
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - public-ip-pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer
  namespace: metallb
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 192.168.1.1
  bfdProfile: bfd-profile
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: bfd-profile
  namespace: metallb
spec:
  receiveInterval: 380
  transmitInterval: 270
