apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.13.3
      helm:
        valueFiles:
          - $repo/core/cert-manager/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: core/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
