apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: no-sync
  sources:
    - repoURL: https://github.com/davydehaas98/gitops
      targetRevision: HEAD
      ref: repo
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.7.2
      helm:
        valueFiles:
          - $repo/core/ingress-nginx/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: core/ingress-nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
