apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.13.12
      helm:
        valueFiles:
          - $repo/core/metallb/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: core/metallb

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb

  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
