postgresql:
  auth:
    enablePostgresUser: true
    replicationUsername: repl_user
    existingSecret: postgresql-credentials
    usePasswordFiles: true

  architecture: standalone

  containerPorts:
    postgresql: 5432

  primary:
    standby:
      enabled: false

    containerSecurityContext:
      enabled: true
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: []

    persistence:
      enabled: true
      mountPath: /bitnami/postgresql
      accessModes:
        - ReadWriteOnce
      size: 8Gi

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  networkPolicy:
    enabled: false

  volumePermissions:
    enabled: false

  serviceAccount:
    create: false

  rbac:
    create: false

  psp:
    create: false

  metrics:
    enabled: false
