---
- name: Check if control-plane is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init
  delegate_to: "{{ groups['control_plane'][0] }}"

- name: Copy kubeadm-config.yaml
  when: kubeadm_init.stat.exists == false
  ansible.builtin.copy:
    src: ../../../../kubeadm-config.yaml
    dest: ~/kubeadm-config.yaml
    mode: '644'
  delegate_to: "{{ groups['control_plane'][0] }}"

- name: Initialize the control-plane
  when: kubeadm_init.stat.exists == false
  ansible.builtin.command: kubeadm init --config ~/kubeadm-config.yaml --upload-certs
  delegate_to: "{{ groups['control_plane'][0] }}"

- name: Copy admin.conf
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: '755'
    remote_src: true
  delegate_to: "{{ groups['control_plane'][0] }}"
