createController: true

secretName: "sealed-secrets-key"
keyrenewperiod: "0"

fullnameOverride: "sealed-secrets-controller"

podSecurityContext:
  enabled: true
  fsGroup: 65534

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  pathType: ImplementationSpecific
  hostname: sealed-secrets.local
  path: /v1/cert.pem
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
