config:
  existingSecret: oauth2-proxy-credentials
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    provider = "keycloak-oidc"
    oidc_issuer_url = "https://auth.cloud.davydehaas.dev/realms/master"

serviceAccount:
  enabled: true

ingress:
  enabled: true
  path: /oauth2
  hosts:
    - longhorn.cloud.feddema.dev
    - hubble.cloud.davydehaas.dev
  tls:
    - secretName: longhorn-tls
      hosts:
        - longhorn.cloud.davydehaas.dev
    - secretName: hubble-tls
      hosts:
        - hubble.cloud.davydehaas.dev

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 30m
    memory: 50Mi

proxyVarsAsSecrets: true

securityContext:
  enabled: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 2000

replicaCount: 1

podDisruptionBudget:
  enabled: false

httpScheme: http

sessionStorage:
  type: redis
  redis:
    clientType: standalone
    password: secret

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: secret
