---
- name: Add Kubernetes gpg key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '644'
    force: true

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes
    update_cache: true

- name: Install Kubelet
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
    state: present
    name: kubelet={{ KUBERNETES_VERSION }}-*

- name: Hold Kubelet
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold

- name: Install Kubeadm
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
    state: present
    name: kubeadm={{ KUBERNETES_VERSION }}-*

- name: Hold Kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
