
replicaCount: 1

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    external-dns.alpha.kubernetes.io/hostname: sonarqube.cloud.davydehaas.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
  ingressClassName: nginx
  hosts:
    - name: sonarqube.cloud.davydehaas.dev
      path: /
  tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.cloud.davydehaas.dev

resources:
  limits:
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 2048Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

prometheusExporter:
  enabled: true
  config:
    rules:
      - pattern: ".*"
