apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  stringData:
    admin.password:
    admin.passwordMtime: MjAyMy0xMS0xNFQxODoxODo1OVo=
    oidc.keycloak.clientSecret:
    server.secretkey: a3RTY2wxeWVsWTVjVDA4SGhVNERrTm1mdEJKcGE5OEtlT0diSUdhUFMrMD0=
