- name: Create partition
  hosts: all
  become: yes
  tasks:
    - name: Create primary ext4 partition
      community.general.parted:
        device: /dev/nvme0n1
        number: 1
        flags: [ lvm ]
        state: present
        fs_type: ext4

    - name: Create directory
      ansible.builtin.file:
        path: /mnt/ssd0
        state: directory
        mode: '755'

    - name: Mount partition
      ansible.posix.mount:
        fstype: ext4
        src: /dev/nvme0n1p1
        path: /mnt/ssd0
        opts: defaults
        state: mounted
        boot: true