command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--auto-build"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"
  
replicas: 1

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 1024Mi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: auth.cloud.davydehaas.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  rules:
    - host: auth.cloud.davydehaas.dev
      paths:
        - path: '/'
          pathType: Prefix
  tls:
    - secretName: auth-tls
      hosts:
        - auth.cloud.davydehaas.dev
