
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: pihole.cloud.davydehaas.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
  path: /admin
  hosts:
    - pihole.cloud.davydehaas.dev
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.cloud.davydehaas.dev

persistentVolumeClaim:
  enabled: true
  accessMode: ReadWriteOnce
  size: 500Mi

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
