apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBQwtvFM43RpQMCWwSj7lKohhV4sns/t6SSQtrTgmW0Fk9RejzNR37Ae+Jzb6pYc0OE1YCFCw+kADrMXWUYMf7OiUJGJlzSBCL4VsSy9KbP7/B+R04lvV3W5Cdks53HLkCFErdR4vbBQWA35X9e9+NRUT64phd6TkVbhxgEMLyj7GGA8p+e+E3IIZ2+JjQqYsaFiTAD4UyqCLQFn/o7POcZvWR/eB+5zSywuYF8gJh02q6ubtIJxI4qCmn3SNhtqycb1SfZL8amgPVW1M590xfLHw43zP+HGplAtF4zVzSeZNO+ygSS3Y4pwvBukbbPV1M3swsudYYYlFCCxr/JPjFLqXCN29yKLO+y3iDCUq1eKDAPW7m+AGc2rpogUf2KxMcwim0Tet5UkXxyBJTRNqDrnY/xbORQF+KzTHM3JzAXSiDMt0uTfY7oc1czFvcKdtGhA75M6KsDEkNqbFSD84NAVr1atpE6AQhtdl0lAloLKz5mlNmY4Ebf8dqsPeWMYv9JataRXxoUjoJ5B7YiRM1czsVAHKIzpqRFu4A3VGlmAg09OZ8NnkS32JliOK3bHl6v1NNehcPXprX7jJiELnX9VECaq3tgIUd68r8jMalC04AM/qkB3f3Sc/v3iPTpMFV0Zoqubo+3VJh15RMYwZoujJpeWFLHdelSPlcOifk+TFi0u5IjzTuwiFYKoF8Jrg6Chx1wckehCfDIhhopTeD24MrNyECGfF3uKi33hx3BCRLH8nUW8Q4g
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
