apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBXvX+uAHRXnicstUd/NFlR25uOrsGczGSDEjgddgOrjn64vGByXzmeQSzlro+TKyiSlgpGGWkMQye2JofFwvwaS3SClbEsEmta2+FX7uqi03KqESZren0AHWvrEZe6OvvOCrceUbrPbNKCSBrSXs2Yrd4FhftuHzcivB4iEe/9VLSfVBFxg7ou0c9QhNU9MIcc70NiOMSMteNSZRyDBT1mnriT0vyGZWrkThEgXxMLlPa7DULlSFbZJNHAMaShMQQ862ChylHm24zASciekuVx0nHBU7epiMaDIb/ueIuBIyg4jFDLTGpLEJg99KdkBlQvrG0vw7K1ukmWAOm0P/wjKpgbUocSyKAtaKB3hs5k0cgRkxTmcZkgq8OKGA9zu1EqKElqJuDWYCM6WvySzHiz2X2jpWYtOglmmL4lKzkVEPovTNl1xZUxivXzg0M2gDcyTHzRAKiMyaqaZ8wdu7MoDPmHuWn8ECVP87hLpg3lpbss8TKGO0yaElvycVBedhQ0t1k9OAZkAZtpmjkVlmkTfNdgIYeaO70vpzoM31HLtfCdK1yxjwmXdhnFJXLjsGTgqtRqYgnJU44RsMt2ZA81VRuRcJcPmreP05nkhIQfKKOJ3aesOQFIr9tPJ9nECbuaySB+2fv9T1O2rtZ8pi0MlIKoZS6NlmI76xHJ6B/4eyiUzTV7DoHMS+AU3Y31a7dcNvu6SSA1P9hU0kKGtvriutwOqkI//QVJfpUPtwFx1r2CYrg0lnma
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
