apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAqlxVwfrufbBWuxkew0CZlnyNn6c+fwc75JVETg6nYVhVX70x8KEQeS9JnBPXoSg9YRAZopUTFPWQKecx+2tUItv7bVNc9LP2drVvinXK7O37JmyLf1Mr6qRWy8JAVrZPABOOSOrogHFUodkzoXZI40UAfyXOVgu8/J8aOwnnp3jIFwLoJcBCMdj496lOwq6Qye3NqGxWICATXl6ZN+JQXsU78Naaz/DLRvxFxfDIusz/MSRAen86p9OxBinHEpudACXdOYOxpVh08ZpkzgDOm1OY8iwUaPug5c7noo5lixsw7nZpkUkKQJBm4rd5oaCdko06I+zcGoRPEQ10DDsN090k/kxLx8UPZYV3uqNMuH1PQhA0WgvDaI7nzwiKTKvf6XKUrIn8rMIvc+jUraiVVo3WlEb0QAbNq2ofrwn9hgFiPu6rC/9o1XAaUhmOeJW19wr78jL2F2aMiDiVP5PKh23gGyoSKifqEVFHKdacpX2hbAiMnnZ6nGB6AbDFWvEbpMNRHACZecWQC6F2pBHHVyTfUnom+R+v5A31Pyj/MOfj1PY/GFqMMrSPPJq7g9aBD4XGIUZXv5mN507AHXfI+vm7uijhhtLz9rf840n/dU75a0LEvTrGlR/YLqvQOlgIpndPlzw6kMLLxjr/IbMKc9sa/cpSUrLIqRNBPxGlOMnmoQXHo9ixzeqFJwZpFRmZa09T+3KJWvq7grC4S3pRgXk6u+moiu2Ks+lZJoGtVi6E2EcCYlc74
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
