apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAtvjaO5fQfisysBofoSXHOGWaPNOqHXHwZoLhQUcBi37D5jg3DZlSNiTLzs19UQtYBWgiAI9PzKFXfGJQK7GyW7ZK7DkuYmjD2WIevA548u1/HWUakN6ddqYG58TIeqUqMJJf+ptf5X3Lc8woTMWkSetkqasVUozi/pzmE29qPw45B04IHt4D7HqV48FQgALnF2DCQfatf2HytctxbWGNOECtbghzwhO5LJmJZPMnP+Xgr5S7emIeoU0+6LGjlvC9TH79jF13/3Ja+AHrlLm3RVaazcU2V/hlYcQN3AWYKemv5IKHJaGmvSlwno/HHaDSBkL2elcmaBKuW+WKp37lwH+9au7baKJ0820mtICtMMgRJ/yPwCYqb6ta+UL+mpCNN114JWNSU6AmHicuGADu6InVGLgA+V6O+JD30MQmBSPdAYZ1dUw1isRpe9N3HaSLdKNiht8himRKtJKwxWJhd0a8+Ze251M8GQETqbNmQkU82/MxjR0TxkIepSj7rh18YP6OFyKkpWFJnz4NvwDWVrQlwCrQNjM7femeCRsZhTYE06qYFYzyCsg7ozlIXInf4mMa1qiiddagStI74dX8JdSzLgiR4Vovf8fUXWg2hohwqnRTiyQtDY4Jcu35ciLkSMjgBbIakpR6nNGwH572plEgLdb+GWGzZcgW7Fa26Sg/IMeGcVghq8xhMAETeFCDy1Z2W9RxfhZ6+n/2EdzUYykqVKGHed6ZF7kXwhLqiHIxVzQCkdyJ/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
