apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBfdqf6QCpi0qvHBX6Yw56OflKoucq06By0nqq2y6G67lyIcnV38h5h3x+6NjYswePAX3pJuDzENlN1tKyHiFhnbTmkOCh+JVMrSTKa+gx9ghy9K0YvhP0+4yqxvt7mcyt3Jy6tTMy76C4/dCVdzY+xqJIk4dffBYlq07dvJE0KUPRo1BKs0VxrKlWJyGxUhi1khdnXSiv+zOIKDGU8HkQA99u0WCIDqm7weJN5ZyhF+k3EHthsM6K4vqWWTzlDPjuL51HUZwPsBbUYIE71XOYtUNpuOdnbQGrAmPAsqHk25LS6UzgiE6xyfbLqxk1PJDbEpjXIPob+eAQ+UobLaBubHHFCbgphCkKzAEImGQMxaAPndbHM6kkGwiznsk7oKkVTYm8QtS1WtVzJ12l3QaSUi8bduhpHtmThsTQ/0RcUR/8Yz5fP+a7b+MHI71xbeL5at9g67/NkjkQMxAfYONeCoU/71V3FNq2VTurddEPBPw3UbFrsu1lQy2IfiSHM4c7EqZy5XliVFn4NYKaLHjtem9MNmdwB+hYqbwhTb0JHhfPSj6R/MFR5EmvdRY5BeRgnPI9VuKuPUJ/RtseFnDq2cxexJj7Bl+7csJKZKTwbPyskoR9KGhoQ8ZeT4BaELwvXb0orBRuFKPMnJDz4+KQz+QzFI5XbAQww7SIgM/XL5mv8S9cj3yiDJ9g/ODrUednrwxB6B4pjajsxvrqwugFNjm/mf6QsqZKb70E+t9irVyB5URO+GZ3P
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
