apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: sonarqube
      targetRevision: 4.1.1
      helm:
        valueFiles:
          - $repo/apps/sonarqube/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: apps/sonarqube

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
