apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCGjiLJvSb1rWCwIMs60wIBgWUkLdapK1CaqGetvuqAR2izVDcKWBUrd/MyVWe/XlMQ5bhq8DQXWeoYVJTTJoLYtGZRuQ503V932ZuWqh19s+uaJZr7gMse2Y5Rh2qFp7H35v/L5Z5P9CFWoet8ArEOM++re0UFc0HMnHw+4eRgDf4KBWpCn8HB6SE478q45RMNxOg70HK7lG9X7D2uHMuxvX6A77RfgkezSfBinu315/EBoJ3wi36rKoVQZ3lfIw6SP2sFooysUaXDKENdcKxqlK6EH5R+JH4AIh32XljbuM5rSLPOWaPN54Qyk4t/BYVe7rs4Xw60avguzNFH0mvIRqui4EM7rEwaf9vEH3try0oK9LF6mpN/f+V5zLmRtyKbeZC4Pusn5ug2hezy4jyfar3+uqJ1HfkUxxGMaoc9dDHTTagUhjJPrdijHzlGNcD+bwyJWodB17ymkIN+ac0QvCKkwJpIkilOzjlXmQ7BzWqcGTEzrqIL2F+7l3TKZXxOA8YtnEUELdJY4E2GNZZTI/uM1VcIH9sdTTKdVQxXjo4WWuer39Gu0g5iTV8NmOCIDJLncj23t0EJ8BLCdRS2JqDXdguiTz1+yNTKTmSo0tufI0MMED0ToOcjh5PXsyHSBb0IQdF//5AmHBrryWS16apqq2SngKOnjAIGwJQ2G7gUsJS/tLFOT0voU549ikff2t89A6wCJkzyH0iNuLbF1SDuelGo92dKhjae47bO/v1EKDzx2Eek
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque