apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgB7dKMdUEE4gByKfowPmSRkfEUN/dVOQP735hm77trbOiL9g7+OzwAUwdsXQ+4rmokuoWoIvtvRKujYAcpHnwJRKsPjHw4V9RtUUbaGHYQMKZ9IAJYkq9UOQEYWHyJ6pOdkEQLgAlc4LMIeJUqhrsx2pe2M1nnLbJnGK5CIlhQbAEKZpp4oKcNIhIgbT00faq+jPDotY4N7IGs/0lozjUeVh6EcXRvT8EA1l+NeZh/2Ufa9mLzs1/pWPWgx/KSiKD0Fkxb3nxoIDpPOm1Mtioj5qWqd5V0Bd3r21eix3grRpJ3US8Dc3e053HKyYVbrJO+Poq/J3Cd2BQHKs/h2q7BEE5K8+5ExkGTQkw4VDqHTvKWRcixb5SmHi75ofAn4AnewiN9Fwp190HrKfBRSwJxaG9I0sGsx2FziMS11t5o+0gQN2XEAFICbrJNjMbT/pHt4W6vAxOov1SbJeu8j+8zlCMwRag5EOMKmb0qc5r8vfhCag+Sx3vYYk8SXNmTn/lUthGmRvlDyNYUAr0F/NWCndi+aFIeD7Bw5whdfXWgtotgnxh2SN4kZLF4hfZoinB54fFqhtpuQBhjQKrUd1RD0FfK9sqMtd95YuoOeOWEKIN4yFfMiNHIA/ciy23pt1K+VygjyH0VjivriwkqLPkJjLPQBNhc7z1YvAyYNzHWaqxSELWX/kcQ6WEFARtZzC7qZbg4TVJ2npekNvR2qz7wLCVwwSrbIGrYqb9mQ94u+IP1YRbE8Uljc
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque