---
- name: Prepare cluster
  hosts: cluster
  become: true
  become_user: root
  roles:
    - commons
    - partition
    - configure_kernel
    - containerd

- name: Install Kubernetes
  hosts: cluster
  become: true
  become_user: root
  roles:
    - kubernetes

- name: Configure control plane nodes
  hosts: control_plane_primary
  become: true
  become_user: '{{ USER }}'
  roles:
    - control_plane_primary

- name: Configure control plane replica nodes
  become: true
  become_user: '{{ USER }}'
  hosts: control_plane_replica
  roles:
    - control_plane_replica

- name: Configure worker nodes
  become: true
  become_user: '{{ USER }}'
  hosts: worker_node
  roles:
    - worker_node
