---
- name: Setup cluster
  hosts: cluster
  become: true
  roles:
    - commons
    - partition
    - configure_kernel
    - containerd

- name: Setup Kubernetes
  hosts: cluster
  become: true
  roles:
    - kubernetes

- name: Setup control plane
  hosts: control_plane_primary
  become: true
  roles:
    - control_plane_primary

- name: Setup control plane replica nodes
  hosts: control_plane_replica
  become: true
  roles:
    - control_plane_replica

- name: Setup worker node
  hosts: worker_node
  become: true
  roles:
    - worker_node
