apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno-policies
      targetRevision: 3.0.4
      helm:
        values: |
          podSecurityStandard: restricted
          podSecuritySeverity: high
          validationFailureAction: audit

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
