apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.59.4
      helm:
        valueFiles:
          - $repo/base/grafana/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: base/grafana

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  revisionHistoryLimit: 2
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
