apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.15.1
      helm:
        valueFiles:
          - $repo/base/promtail/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: base/promtail

  destination:
    server: https://kubernetes.default.svc
    namespace: promtail

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
