apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://intel.github.io/helm-charts
      chart: intel-device-plugins-operator
      targetRevision: 0.27.1
    - repoURL: https://intel.github.io/helm-charts
      chart: intel-device-plugins-gpu
      targetRevision: 0.27.1
      helm:
        valueFiles:
          - $repo/apps/intel-device-plugins/values.yaml
    - repoURL: git@github.com:davydehaas98/gitops.git
      targetRevision: HEAD
      path: apps/intel-device-plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-device-plugins

  ignoreDifferences:
    - group: "deviceplugin.intel.com"
      kind: "GpuDevicePlugin"
      jsonPointers:
        - /spec/resourceManager

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
