apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: https://github.com/davydehaas98/gitops
      targetRevision: HEAD
      ref: repo
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.0.5
      helm:
        valueFiles:
          - $repo/apps/kyverno/values.yaml
    - repoURL: https://github.com/davydehaas98/gitops.git
      targetRevision: HEAD
      path: apps/kyverno

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  revisionHistoryLimit: 2
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
