apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  sources:
    - repoURL: https://github.com/davydehaas98/gitops
      targetRevision: HEAD
      ref: repo
    - chart: sonarqube
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 3.2.7
      helm:
        valueFiles:
          - $repo/apps/sonarqube/values.yaml
    - repoURL: https://github.com/davydehaas98/gitops.git
      targetRevision: HEAD
      path: apps/sonarqube

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  revisionHistoryLimit: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
