k8sServiceHost: cloud.davydehaas.dev
k8sServicePort: 6443

kubeProxyReplacement: strict

operator:
  replicas: 1

resources:
  limits:
    cpu: null
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi
