# k8sServiceHost: cloud.davydehaas.dev
k8sServicePort: 6443

kubeProxyReplacement: strict

operator:
  replicas: 1

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

hubble:
  enabled: true

  tls:
    auto:
      method: cronJob

  relay:
    enabled: true
    rollOutPods: true
    resources: {}
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

  ui:
    enabled: true
    rollOutPods: true

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        external-dns.alpha.kubernetes.io/hostname: hubble.cloud.davydehaas.dev
        external-dns.alpha.kubernetes.io/ttl: "120"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - hubble.cloud.davydehaas.dev
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.cloud.davydehaas.dev
