k8sServiceHost: 38.242.242.71
k8sServicePort: 6443

kubeProxyReplacement: strict

certgen:
  ttlSecondsAfterFinished: null

operator:
  replicas: 1

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

hubble:
  enabled: true

  metrics:
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true

  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

  ui:
    enabled: true
    rollOutPods: true

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: hubble.cloud.davydehaas.dev
        external-dns.alpha.kubernetes.io/ttl: "120"
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      hosts:
        - hubble.cloud.davydehaas.dev
      tls:
        - secretName: hubble-tls
          hosts:
            - hubble.cloud.davydehaas.dev
