apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cilium
  namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: cilium
  updatePolicy:
    updateMode: "Off"
