---
- name: Print join command
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['control_plane'][0] }}"

- name: Join control plane
  shell: sudo {{item}} --control-plane
  with_items:
  - "{{ join_command.stdout_lines }}"
