---
- name: Check if control plane is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create kubernetes folders
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: '{{ USER }}'
    mode: '640'

- name: Push Kubernetes Master PKI files to master replicas
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /tmp/kubeadm-ha/
    dest: /etc/kubernetes/
    owner: '{{ USER }}'
    mode: preserve

- name: Print join command
  when: not kubeadm_init.stat.exists
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: '{{ groups["control_plane_primary"][0] }}'
  changed_when: true

- name: Join control plane
  when: not kubeadm_init.stat.exists
  ansible.builtin.command: '{{ join_command.stdout_lines }} --control-plane'
  changed_when: true
