policy-reporter:
  replicaCount: 1
  worker: 5

  resources:
    limits:
      memory: 100Mi
    requests:
      memory: 30Mi
      cpu: 5m

  metrics:
    enabled: true
    mode: detailed

  ui:
    enabled: true
    replicaCount: 1

    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 30Mi
        cpu: 5m

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
        external-dns.alpha.kubernetes.io/hostname: policy.cloud.davydehaas.dev
        external-dns.alpha.kubernetes.io/ttl: "120"
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: policy.cloud.davydehaas.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: policy-tls
          hosts:
            - policy.cloud.davydehaas.dev

  kyvernoPlugin:
    enabled: true
    replicaCount: 1

    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 30Mi
        cpu: 5m

  # database:
  #   type: postgres
  #   secretRef: policy-reporter-credentials

  monitoring:
    enabled: true

  global:
    plugins:
      kyverno: true
