apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCjsJD00Uy3VLnm6B8DfAMnacddensFCFDhuTj6N600enN0OrtnfA8WPezmU+9guJgtLM1FzXkAK03iTfOAOQWWij1GmlzW/v6tBBOaqCW/PFw6C2JTdzHeC7ENCfQxoRGfC9hlwom84cLoXSg6Dkq/A4GwTkmH8tdWYIk1fliJCzTlwom19jlb11kdnolB7ilQfkkN0YenRxDr7O5LUfBvEdVf25lOdSPqBtK6JQX0ofMXICL3I2KiINmY3IntP2XvqmkCx/3ob32NiYwpHOJSIHd/GGmOwwjpGL1pf/o2ld0xZ1Kcb4Hy5vXtXWSW8/z6fAHHXWFkAo27mqplFIUqyRd4pQ0bPO5u0z0fEzQ9BXVxS/q8N7TgFeXyd7PiannHCXw9YI22k7Dokv93w6tGNkgEmHyod+GKvG0jM07cmBkqu67OH0TVXevBbQ1en5d+/1+2OW5FVimt0IcbiDNW6AjI9UQXfUbnbNNi5rIxPRzevA3GL6v2tsG22FOdo2YBcXMVhv0fu71ZaBAjaJKZA8iexpwbZl58uD1KP4Z1mSh2wOBtWBALwh0muR7hClj3iWjir3SIICFtK/T/QiFlYRgkdQzUNUzdHyQ7EOm5d30nHYXBMi4sONHzcJORExNspKSEvhOl4EZ99tiawrLcPfxBX+s+6T9w7wgl5/DH/wj0w5DPsUgrB5iJZ0yCe9Ut57npKy5tSJUfe5Lt5XjIaVitfA==
    admin-user: AgBGYQjhARJYUrnwbBfWJNnvzOg9zd0pHXAGrXHV/Pisg8DRE793AJt0k4Ty0Rt75Oo41SLhhSzdtShruTUdtBc0yfAFTzyYHcPFLNXo7erx5YM05sMVtxwKjdhffQGEZ8HEfeMjyn0/lzNweied8tMz6Ls0SWwaHwQD8f5GxlNTSxXQsWvNIAOWUtU+ZjRG17zZQlgnX9kuHMULeK/eh/AoL2flc+AREkO5hcoF1z9HzLzYUIoilFRocX/sdt6BDlG9XIPu0G2Lz4Lv4g3e6DSYV1qdM9cGlecR8eQfUxHvwOKa0wvv1h95cH9zBfVcGbSpO0bcaph+xh00NtM4uW4WGkqtlnASj0PlBXB9UzujZF4c/7zFQoLN9zwNSIrSXuoVAP5MAONJgwEPH/iZL4GvgCe9lrM4UfJSSWdAcwt3Nw4Ywxpb8z9bAnDm4Cr0CyTgSUxE7jTxarw+I8DIa46kG78ucIO0cNd5LCrCHecLMWQl1aPN/4Jn1li/5TaV++ZqHOo3ylqswkfzaV+rzLI0Pi5O+bz2p3VhfRtrRwl15xkVaMG/O7Ww9vHRSPkBg4kS3XPbjLx24ua94sq+GTbQt8Trsyvt27IjlqkUH0qGQpidLzScglgWbFOgpHHQ1igsMidXyQ+Lr5f0kMkO//M8/4mnKZqr0i4EligBksUMFqmdSvlNLsfUGa60Rvd1rR9Yfkbblg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: grafana
    type: Opaque
