apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgA/cZc5jM/YjA7k/abDVLvTQO7x2OAkAFuX4VXw9uHlFIX3U1rFyTZAIQxFbiiDnLP3GH5LAtH7XkHhzfvlLKhWo43X3EAVgkOS6UUMeX+7CUN/n9u57BALxXPTzqswuzlCqVQrpY3KqVCK+c/DPdMSjKMZmrAFvltgWWkvjXdjybAAlPZ9HXKvjkoarqj5zX1cMdpydd/4Y+GsnQzW8+RU7Ey5/guZS4RKjJ09c7n91xNro09qpKUIScgG8ko7hnQVpFRfV/F2GYaQoZZdb//a3ptNJuGUFmvLnE8w960avJYUCqSh/59kakwHrlWeprUwYEEuqDoxBw+bhzXDB6vxDnNJf4VipN786jQ7mPOJY4wTtFF/rH8MGkljNIHAhLPRqvku3fzSlRyEJKh7yzG7g3lmzbXD48HM6nO7R0kfxAssuLpVJksNyVOZPlTzLFTP+HRPNz6bmSGZD0ccXEDtC3SY87Qkm9NWzTbulvuXDXLk5DTVP5DyJ2H0OlL6/FMQ8aIDc18jqzOTA6e0GhnjM1qOvRkdfAiWNagYz5ciy8whbaMrYFPPwpBxS07cZtz2t7h1h8UUEHBYZnLZjYT+Udy64obUkQqsn6R8DoQZ8qe2qxd6rZrAKGF2yyEkqJis1OeVZWS7HttdWvC4tqv04JJazbTyAK+O257qcffsl3bRDCGXUnCqLTocmxA9f10Tu3QgrRLWBfV7swqeWomQMgaWUg==
    replication-password: AgAXvM6dK3Uq8lgB2USqjLFPOLF2XOVv4a0kwzeglz80J+2ErtK0DHhhhV3jZO1seNFgdBg9jTmmfKET+VNAj5FaTSFb2R18B0sxsPZW+N9vnQa+Ec1zQsY3t8WJ19zZ9IeIYPZs25295t75uzSWUJwSL3Q8ddT2tO7GEd/zg8mDvzVBVXUKy6YIlNs83z2FeG/8JUYgRgObMQR7432JYfifhiY/8YLRNwxC166hHabuhPdjt6fxnYwQZTX0X3SQIwUzHE5aSK2AsYp5U1k30I9QSLbaw0DJmwy7mtrrHJiHPny3U6L0Nz8XfNJZfgus6LdS2KCUQVFt0izO2HxG6gOwKmtXv4cwNuwrF22RhCsHNkpH7sr/ZOPiAtlR7PFgq6B7fL1ih27pzzTFCyLCPXK0Ch7RQYfxoXryvSsmZHYG/6ivq90oG/v711XiywSvisE1fE7HtNbmC36y1gh0wI4mbVTD58Gjiw+0WORG7LP/diez7aCaz/f5gIjbyP2avdlScUJdKZfosI9PZh65bHLUomaL4hsB06jNh9HmsA+NEapD8VAtgs1V3V89vHZw3Vy1zyx8zU8XssBl99iWCc6GEll8Dp+vLLhSP9yb1X72Bt/9uZ/Mvq7oo9o3MFW4LfrAy7MO0lA251AygCGBpVEMBsX287ngnIOLGmK7TSEo1AyIjfAPQTTCz1h3Ff9a2c7DHCgJH5VPI4566lQheA82CHalrg==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: postgresql
    type: Opaque
