apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgAjO+lWHILGnj3rr6rvzgeL4UazDphZyJeQO3gos9zBNKouLH8ryie6rzxgGbIfSzvVMaRtPYjCWpaxLXyzcNXBpc4q0JRiVrglwoVOH0Dq5acZxUTuzHxvLvUpZcCzuQqdnEk+6xttb/f8UrnLG5d6O9pJOxQjHk4Qf4wKPoL33wCVavVecBPoirxOMsRiuiDTZr8iR0C9p09Ir9SoRf6dRZgePzZj+G1HIDjbUkqqTNw5WKW9WmjEwGKBIMUXF8q2+rHGUrdgLkNndkgXlfHEzRcwg9gh2oAQmjjW5bZNFBy1HW8xoacPhvxB9VUN1I4bOICNTWC7yZ5JOS48WHBTNrt1krwytGiJpw1pIb7LbcggY8QwW1T8ByaqHkW4gX//0a2wFc4MT7sCAwrhrPq5Ii+A7Tfjb68isv8vjjs1PoxJVDfdLvKHxFRMpqjKI+CYm0TAEP+swZSnnD9Oadki+jpAa0fE8HVwRQBHyewVic5akmMJ1VHoV+WK9amyYdwOuVQoj+ne++FCYny/3v5reYicSOoVcNsPdmNRXKwtCG6GFbEFufNO+IDsyLD5LadSRaAsp+QoFcsvvDyWPcg2yCUUj2q9j4HGCqxeocwIj09xNdiE5J92RLEpxhyhiTcJxBk9XQQukoqioCtce7sYpSAxBhs5Q+V8W7odKZX3zg6ugEmtK7M6fWVOa53fBxcrr/EQKMo3EJKG2D6WQS6jc8FAKQ==
    replication-password: AgBGid+73LbWNXFZeXC5nGCVxzSEMDCWmh809ETPq/u6frtnjTF0Y2kVsm89BjHvObGxFeNSgQQQMcA7PgWXh65JIiSEHq6yiHyMwV9tCdrIBFCeywURzPT0b/7ek8n+oEUFD1L7cQVj5mAaAPHcyeuBCYTfow0JVEzCLH/2ZUb0iQSph65IjmDbl8seBCPA5d0m4b2uZLyKcz9THS8eqn3qVc/fBwFlV/JBXlJSWpZ87Aa46jaC4fLkSPNNrQ6cZKl9czhWKFCWYXpdBiCqp1KTxirCFOEu6H88bCDhH30f5WUhxzywRXrSKqDiJFkpN7/YM7c2WBU18yhoqKtVYmcHUbRT163EIFLHLI4K53DiBELQ+5BjJa+mLQ2rLwqHxeDJPkDqxCLc/xD137meMFRArLstGl5sKmQ5sn6UU57bd/jKc0Ud1LN3CSjLYjFJi8RXFOA3QiOkF0uW4KG+uHS4P4AwZMUu6aeQ2EUee8gT6xuECfR3dmBO7D78R3SsezyUQug2weDPY9wKdAB0TYvYT3p50ndB3ocsjp5F1oe6BqXXDoKAG5G1JW3mr9bSKqkvDr7V6mw60q7qYo1HcE8q8zQ97Ao0p1Mmw1LRGrCo7cAPKIr++5RQvAHfXbgfVUG1iQyskRCx+9TFdRjU8EMpUkoJX6voJ+vTgHMbaLqKWMPifMcCQU7dlu5gPZHgxdIR7l8FYnqXt6vZht94SbXfKkjbaQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: postgresql
    type: Opaque
