auth:
  enablePostgresUser: true
  replicationUsername: repl_user
  existingSecret: postgresql-credentials
  usePasswordFiles: true



resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
