sealed-secrets:
  createController: true

  secretName: "sealed-secrets-key"
  keyrenewperiod: "0"

  fullnameOverride: "sealed-secrets-controller"

  ingress:
    enabled: faslse

  serviceAccount:
    create: true

  rbac:
    create: true
    pspEnabled: false

  metrics:
    serviceMonitor:
      enabled: true

    dashboards:
      create: true
