# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.12.3
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yaml
      - name: Run ansible-playbook syntax-check
        run: cd ./ansible && ansible-playbook playbook.yaml --syntax-check
      - name: Run ansible-lint
        run: ansible-lint ./ansible/playbook.yaml
