# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Lint playbook
        run: |
          ansible-playbook /ansible/playbook.yaml --syntax-check
          ansible-lint /ansible/playbook.yaml
