# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Lint playbook
        run: |
          cd ./ansible
          ansible-playbook playbook.yaml --syntax-check
          ansible-lint playbook.yaml
